apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-agent-remediator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-agent-remediator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "go-agent-remediator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-agent-remediator.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "go-agent-remediator.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
          args:
            - --metrics-bind-address=:8443
            - --leader-elect
            - --health-probe-bind-address=:8081
            {{- if or .Values.logging.enableAudit (gt (.Values.logging.verbosity | int) 0) }}
            - -v={{ max (.Values.logging.verbosity | int) (ternary 1 0 .Values.logging.enableAudit) }}
            {{- end }}
            - --api-token-secret={{ .Values.nirmata.apiTokenSecret }}
            {{- if .Values.nirmata.apiTokenSecretNamespace }}
            - --api-token-secret-namespace={{ .Values.nirmata.apiTokenSecretNamespace }}
            {{- end }}
            {{- if .Values.nirmata.endpoint }}
            - --url={{ .Values.nirmata.endpoint }}
            {{- end }}
          ports:
            - containerPort: 8443
              name: metrics
              protocol: TCP
            - containerPort: 8081
              name: health
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 