{{- if .Values.llm.enabled }}
apiVersion: serviceagents.nirmata.io/v1alpha1
kind: LLMConfig
metadata:
  name: {{ include "go-agent-remediator.name" . }}-llm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-agent-remediator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.llm.provider | quote }}
  {{- if eq .Values.llm.provider "bedrock" }}
  bedrock:
    model: {{ .Values.llm.model | quote }}
    region: {{ .Values.llm.region | quote }}
    {{- if .Values.llm.secretName }}
    secretRef:
      name: {{ .Values.llm.secretName | quote }}
      {{- if .Values.llm.secretKey }}
      key: {{ .Values.llm.secretKey | quote }}
      {{- end }}
    {{- end }}
  {{- else if eq .Values.llm.provider "azure-openai" }}
  azureOpenAI:
    endpoint: {{ .Values.llm.endpoint | quote }}
    deploymentName: {{ .Values.llm.deploymentName | quote }}
    secretRef:
      name: {{ .Values.llm.secretName | quote }}
      key: {{ .Values.llm.secretKey | default "api-key" | quote }}
  {{- end }}
{{- end }}

