{{- if .Values.remediator.enabled }}
apiVersion: serviceagents.nirmata.io/v1alpha1
kind: Remediator
metadata:
  name: {{ .Values.remediator.name | default (include "go-agent-remediator.name" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-agent-remediator.labels" . | nindent 4 }}
spec:
  environment:
    type: {{ .Values.remediator.environment.type }}
  {{- if .Values.remediator.target }}
  target:
    {{- if eq .Values.remediator.environment.type "localCluster" }}
    localClusterTarget:
      repoNamespaceMappingRef:
        name: {{ .Values.remediator.target.localClusterTarget.repoNamespaceMappingRef.name | default "repo-namespace-mapping" }}
        namespace: {{ .Values.remediator.target.localClusterTarget.repoNamespaceMappingRef.namespace | default .Release.Namespace }}
        {{- if .Values.remediator.target.localClusterTarget.repoNamespaceMappingRef.key }}
        key: {{ .Values.remediator.target.localClusterTarget.repoNamespaceMappingRef.key }}
        {{- end }}
    {{- else if eq .Values.remediator.environment.type "argoHub" }}
    argoHubTarget:
      {{- if .Values.remediator.target.argoHubTarget }}
      {{- if .Values.remediator.target.argoHubTarget.clusterNames }}
      clusterNames:
        {{- toYaml .Values.remediator.target.argoHubTarget.clusterNames | nindent 8 }}
      {{- end }}
      {{- if .Values.remediator.target.argoHubTarget.clusterServerUrls }}
      clusterServerUrls:
        {{- toYaml .Values.remediator.target.argoHubTarget.clusterServerUrls | nindent 8 }}
      {{- end }}
      {{- with .Values.remediator.target.argoHubTarget.argoAppSelector }}
      argoAppSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  remediation:
    triggers:
      - schedule:
          crontab: {{ .Values.remediator.remediation.schedule | quote }}
    {{- if .Values.remediator.remediation.matchSeverity }}
    filters:
      policySelector:
        matchSeverity:
          {{- toYaml .Values.remediator.remediation.matchSeverity | nindent 10 }}
    {{- end }}
    llmConfigRef:
      name: {{ include "go-agent-remediator.name" . }}-llm
      namespace: {{ .Release.Namespace }}
    gitCredentials:
      name: {{ .Values.tool.name | default (printf "%s-github" (include "go-agent-remediator.name" .)) }}
      namespace: {{ .Release.Namespace }}
    actions:
      {{- range .Values.remediator.remediation.actions }}
      - type: {{ .type }}
        {{- if or (eq .type "CreatePR") (eq .type "DryRun") }}
        toolRef:
          name: {{ .toolRefName | default $.Values.tool.name | default (printf "%s-github" (include "go-agent-remediator.name" $)) }}
          namespace: {{ $.Release.Namespace }}
        {{- end }}
      {{- end }}
{{- end }}

