{{- if .Values.admissionController.apiPriorityAndFairness }}
apiVersion: {{ template "kyverno.flowcontrol.apiVersion" . }}
kind: PriorityLevelConfiguration
metadata:
  name: {{ template "kyverno.admission-controller.name" . }}
  labels:
    {{- include "kyverno.admission-controller.labels" . | nindent 4 }}
{{- $commonAnnotations := include "kyverno.annotations.common" . | nindent 4 }}
{{- if $commonAnnotations }}
  annotations:
{{ $commonAnnotations }}
{{- end }}
{{- with .Values.admissionController.priorityLevelConfigurationSpec }}
spec:
  {{- tpl (toYaml .) $ | nindent 8 }}
{{- end }}
{{- end }}
