{{- if .Values.kyverno.admissionController.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kyverno.admission-controller.roleName" . }}
  namespace: {{ template "kyverno.namespace" . }}
  labels:
    {{- include "kyverno.admission-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
    resourceNames:
      - {{ include "kyverno.config.configMapName" . }}
      - {{ include "kyverno.config.metricsConfigMapName" . }}
      - license-check-success
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - patch
      - update
  # Allow update of Kyverno deployment annotations
  - apiGroups:
      - apps
    resources:
      - deployments
      {{- if .Values.kyverno.webhooksCleanup.enabled }}
      {{- if not .Values.kyverno.templating.enabled }}
      - deployments/scale
      {{- end }}
      {{- end }}
    verbs:
      - get
      - list
      - watch
      {{- if .Values.kyverno.webhooksCleanup.enabled }}
      {{- if not .Values.kyverno.templating.enabled }}
      - patch
      - update
      {{- end }}
      {{- end }}
{{- end -}}
