{{- if and (eq .Values.kyverno.admissionController.rbac.create true) (not .Values.rbac.operatorHasAdminPerms) (contains "v1.10" .Values.kyverno.image.tag) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kyverno110.admission-controller.roleName" . }}
  namespace: {{ template "kyverno.namespace" . }}
  labels:
    {{- include "kyverno110.admission-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
    resourceNames:
      - {{ include "kyverno110.config.configMapName" . }}
      - {{ include "kyverno110.config.metricsConfigMapName" . }}
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - patch
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - patch
      - update
  # Allow update of Kyverno deployment annotations
  - apiGroups:
      - apps
    resources:
      - deployments
      {{- if .Values.kyverno.webhooksCleanup.enabled }}
      - deployments/scale
      {{- end }}
    verbs:
      - get
      - list
      - watch
      {{- if .Values.kyverno.webhooksCleanup.enabled }}
      - patch
      - update
      {{- end }}
{{- end -}}
