{{- if .Values.tlsCert }}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-registrator
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data: 
    tls.crt: |
        {{ .Values.tlsCert | b64enc }}
    tls.key: |
        {{ .Values.tlsKey | b64enc }}
{{- end }}
