# # Default values for nirmata-kube-controller.
# # This is a YAML-formatted file.
# # Declare variables to be passed into your templates.

nirmataURL: "wss://nirmata.io/tunnels"
namespace: "nirmata"
global:
  imageRegistry: ghcr.io
  imageRepository: nirmata
  registryUserName:
  registryPassword:

kubeController:
  imageRegistry:
  imageRepository:
  imageTag:

otelAgent:
  imageRegistry:
  imageRepository:
  imageTag: "0.92.0"
# cluster name is required
cluster:
  name: ""
  type: default-policy-manager-type
  labels:
    # key: value
    # key2: value2

apiToken: ""

features:
  policyExceptions:
    enabled: false
  policySets:
    enabled: false

readWriteMode: false

proxy:
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""
