apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cloud-control.reportsController.name" . }}
  namespace: {{ template "cloud-control.namespace" . }}
  labels:
    control-plane: controller-manager
  {{- include "cloud-control.reportsController.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.reportsController.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "cloud-control.reportsController.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "cloud-control.reportsController.labels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args: {{- toYaml .Values.reportsController.args | nindent 8 }}
        image: "{{ .Values.reportsController.image.registry }}/{{ .Values.reportsController.image.repository }}:{{ .Values.reportsController.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.reportsController.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: reports-controller
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.reportsController.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.reportsController.securityContext | nindent 10 }}
      {{- if .Values.reportsController.imagePullSecrets }}
      imagePullSecrets:
        {{ range $name, $secret := .Values.reportsController.imagePullSecrets }}
        - name: {{ include "cloud-control.reportsController.name" $ }}-{{ $name }}
        {{- end }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ template "cloud-control.reportsController.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
