apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "cloud-control.reportsController.name" . }}-reports-controller-role
  labels:
  {{- include "cloud-control.reportsController.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - nirmata.io
  resources:
  - imageverificationpolicies
  - validatingpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - reports.kyverno.io
  resources:
  - clusterephemeralreports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - wgpolicyk8s.io
  resources:
  - clusterpolicyreports
  - clusterpolicyreports/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "cloud-control.reportsController.name" . }}-reports-controller-rolebinding
  labels:
  {{- include "cloud-control.reportsController.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "cloud-control.reportsController.name" . }}-reports-controller-role
subjects:
- kind: ServiceAccount
  name: {{ template "cloud-control.reportsController.serviceAccountName" . }}
  namespace: {{ template "cloud-control.namespace" . }}
