apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cloud-control.reportsController.serviceAccountName" . }}
  namespace: {{ template "cloud-control.namespace" . }}
  labels:
  {{- include "cloud-control.reportsController.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.reportsController.serviceAccount.annotations | nindent 4 }}
