{{- if .Values.admissionController.metricsService.createServiceMonitor }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-control.admission-controller.name" . }}-metrics-service
  namespace: {{ template "cloud-control.namespace" . }}
  labels:
    control-plane: controller-manager
  {{- include "cloud-control.admission-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.admissionController.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "cloud-control.admission-controller.matchLabels" . | nindent 4 }}
  ports:
	{{- .Values.admissionController.metricsService.ports | toYaml | nindent 2 }}
{{- end }}
