{{- if .Values.backgroundController.enabled -}}
{{- if .Values.backgroundController.metricsService.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kyverno.background-controller.name" . }}-metrics
  namespace: {{ template "kyverno.namespace" . }}
  labels:
    {{- include "kyverno.background-controller.labels" . | nindent 4 }}
{{- $commonAnnotations := include "kyverno.background-controller.serviceAnnotations" . | nindent 4 }}
{{- if $commonAnnotations }}
  annotations:
{{ $commonAnnotations }}
{{- end }}
spec:
  ports:
  - port: {{ .Values.backgroundController.metricsService.port }}
    targetPort: 8000
    protocol: TCP
    name: metrics-port
    {{- if and (eq .Values.backgroundController.metricsService.type "NodePort") (not (empty .Values.backgroundController.metricsService.nodePort)) }}
    nodePort: {{ .Values.backgroundController.metricsService.nodePort }}
    {{- end }}
  selector:
    {{- include "kyverno.background-controller.matchLabels" . | nindent 4 }}
  type: {{ .Values.backgroundController.metricsService.type }}
{{- end -}}
{{- end -}}
