{{- if .Values.rbac.create }}
{{- if .Values.rbac.operatorHasAdminPerms }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "enterprise-kyverno.fullname" . }}
  labels:
    {{- if .Values.globalLabels }}
    {{- toYaml .Values.globalLabels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.globalAnnotations }}
    {{- toYaml .Values.globalAnnotations | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ template "enterprise-kyverno.rbac.serviceAccountName" . }}
  namespace: {{ template "enterprise-kyverno.namespace" . }}
{{- else }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "enterprise-kyverno.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "enterprise-kyverno.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "enterprise-kyverno.rbac.serviceAccountName" . }}
  namespace: {{ template "enterprise-kyverno.namespace" . }}
{{- end }}
{{- end }}
