{{- if .Values.imageScanAdapter.createCR }}
apiVersion: security.nirmata.io/v1alpha1
kind: KyvernoAdapter
metadata:
  annotations:
  labels:
    {{- include "enterprise-kyverno.labels" . | nindent 4 }}
    {{- if .Values.globalLabels }}
    {{- toYaml .Values.globalLabels| nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.globalAnnotations }}
    {{- toYaml .Values.globalAnnotations | nindent 4 }}
    {{- end }}
  name: image-scan-adapter-config
  namespace: {{ template "enterprise-kyverno.namespace" . }}
spec:
  adapterType: Vulnerability
  namespace: {{ include "image-scan-adapter.namespace" . }}
  repository: {{ .Values.imageScanAdapter.image.repository }}
  version: {{ .Values.imageScanAdapter.image.tag }}
  replicas: {{ .Values.imageScanAdapter.replicas }}

  helm:
    values:
      scanAll: true
{{- end }}
