---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-operator-pre-upgrade-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-operator-pre-upgrade-hook
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
  verbs: ["delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-operator-pre-upgrade-hook
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": before-hook-creation
subjects:
- kind: ServiceAccount
  name: kyverno-operator-pre-upgrade-hook
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kyverno-operator-pre-upgrade-hook
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kyverno-operator-pre-upgrade-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-timeout": "300"
spec:
  template:
    metadata:
      name: kyverno-operator-pre-upgrade-hook
    spec:
      serviceAccountName: kyverno-operator-pre-upgrade-hook
      automountServiceAccountToken: false
      containers:
      - name: pre-upgrade-hook
        image: "ghcr.io/nirmata/kubectl:1.31.1"
        command: ["/bin/sh", "-c"]
        args:
        - |
          {{- if .Values.secureOperator }}
          kubectl delete validatingwebhookconfigurations --all --ignore-not-found
          kubectl delete mutatingwebhookconfigurations --all --ignore-not-found
          {{- end }}
        env:
        - name: KUBERNETES_SERVICE_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: OnFailure 