{{- if .Values.enableWebhook }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "enterprise-kyverno.fullname" . }}
  namespace: {{ template "enterprise-kyverno.namespace" . }}
  {{- if .Values.globalAnnotations }}
  annotations: 
    {{- toYaml .Values.globalAnnotations| nindent 4 }}
  {{- end }}
  labels:
    {{- include "enterprise-kyverno.labels" . | nindent 4 }}
    {{- if .Values.globalLabels }}
    {{- toYaml .Values.globalLabels| nindent 4 }}
    {{- end }}
  {{- if .Values.globalAnnotations }}
  annotations: 
    {{- toYaml .Values.globalAnnotations| nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "enterprise-kyverno.selectorLabels" . | nindent 4 }}
{{- end }}
