{{- if .Values.rbac.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "enterprise-kyverno.rbac.serviceAccountName" . }}
  namespace: {{ template "enterprise-kyverno.namespace" . }}
  {{- if .Values.globalAnnotations }}
  annotations: 
    {{- toYaml .Values.globalAnnotations| nindent 4 }}
  {{- end }}
  labels:
    {{- if .Values.globalLabels }}
    {{- toYaml .Values.globalLabels| nindent 4 }}
    {{- end }}
{{- end }}
