apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cloud-control.scanner.name" . }}
  namespace: {{ template "cloud-control.namespace" . }}
  labels:
    control-plane: controller-manager
  {{- include "cloud-control.scanner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.scanner.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "cloud-control.scanner.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "cloud-control.scanner.labels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args: {{- toYaml .Values.scanner.args | nindent 8 }}
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        {{- if .Values.scanner.debug.mode }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ quote .Values.scanner.debug.awsAccessKeyId }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ quote .Values.scanner.debug.awsSecretAccessKey }}
        - name: AWS_SESSION_TOKEN
          value: {{ quote .Values.scanner.debug.awsSessionToken }}
        {{- end }}
        image: "{{ .Values.scanner.image.registry }}/{{ .Values.scanner.image.repository }}:{{ .Values.scanner.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.scanner.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: scanner
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.scanner.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.scanner.securityContext | nindent 10 }}
      {{- if .Values.scanner.imagePullSecrets }}
      imagePullSecrets:
        {{ range $name, $secret := .Values.scanner.imagePullSecrets }}
        - name: {{ include "cloud-control.scanner.name" $ }}-{{ $name }}
        {{- end }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ template "cloud-control.scanner.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
