{{- if and .Values.scanner.primaryAWSAccountConfig.accountID .Values.scanner.primaryAWSAccountConfig.accountName (not (empty .Values.scanner.primaryAWSAccountConfig.regions)) (not (empty .Values.scanner.primaryAWSAccountConfig.services)) }}
apiVersion: nirmata.io/v1alpha1
kind: AWSAccountConfig
metadata:
  name: "{{ .Values.scanner.primaryAWSAccountConfig.accountName | lower | replace " " "-" }}-{{ .Values.scanner.primaryAWSAccountConfig.accountID }}"
spec:
  scanInterval: {{ .Values.scanner.primaryAWSAccountConfig.scanInterval | default "1h" }}
  accountID: "{{ .Values.scanner.primaryAWSAccountConfig.accountID }}"
  accountName: {{ .Values.scanner.primaryAWSAccountConfig.accountName }}
  regions:
    {{- range .Values.scanner.primaryAWSAccountConfig.regions }}
    - {{ . }}
    {{- end }}
  services:
    {{- range .Values.scanner.primaryAWSAccountConfig.services }}
    - {{ . }}
    {{- end }}
{{- end }}
