apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cloud-control.scanner.serviceAccountName" . }}
  namespace: {{ template "cloud-control.namespace" . }}
  labels:
  {{- include "cloud-control.scanner.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.scanner.serviceAccount.annotations | nindent 4 }}