apiVersion: v2
type: application
name: kyverno-aws-chart
version:  v1.12.1
appVersion: v1.10.5-n4k.nirmata.2
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
description: Kubernetes Native Policy Management
keywords:
  - kubernetes
  - nirmata
  - policy agent
  - policy engine
  - validating webhook
  - admissions controller
home: https://kyverno.io/
sources:
  - https://github.com/nirmata/kyverno
maintainers:
  - name: Nirmata
    url: https://nirmata.com/
engine: gotpl
kubeVersion: ">=1.23.0-0"
