apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kyverno.name" . }}-cleanup-jobs
  namespace: {{ template "kyverno.namespace" . }}
  labels:
    {{- include "kyverno.labels.merge" (list (include "kyverno.labels.common" .) (include "kyverno.matchLabels.common" .)) | nindent 4 }}
{{- $commonAnnotations := include "kyverno.annotations.common" . | nindent 4 }}
{{- if $commonAnnotations }}
  annotations:
{{ $commonAnnotations }}
{{- end }}
