apiVersion: v1
kind: Service
metadata:
  name: {{ template "cloud-control.events-controller.serviceName" . }}
  namespace: {{ template "cloud-control.namespace" . }}
  labels:
    control-plane: controller-manager
  {{- include "cloud-control.events-controller.labels" . | nindent 4 }}
  {{- if and (eq .Values.cloudProvider "AWS") (eq .Values.eventsController.service.type "LoadBalancer") }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  {{- end }}
spec:
  type: {{ .Values.eventsController.service.type }}
  selector:
  {{- include "cloud-control.events-controller.matchLabels" . | nindent 4 }}
  ports:
	{{- .Values.eventsController.service.ports | toYaml | nindent 2 }}