{{- if .Values.eventsController.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cloud-control.events-controller.serviceAccountName" . }}
  namespace: {{ template "cloud-control.namespace" . }} 
  labels:
    {{- include "cloud-control.events-controller.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.scanner.serviceAccount.annotations | nindent 4 }}

{{- end }}
