kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kyverno.name" . }}-installer
  namespace: {{ include "kyverno.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kyverno.name" . }}-installer
subjects:
- kind: ServiceAccount
  name: {{ template "enterprise-kyverno.rbac.serviceAccountName" . }}
  namespace: {{ template "enterprise-kyverno.namespace" . }}
