{{- if .Values.admissionController.enabled -}}
{{ range $name, $secret := .Values.admissionController.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloud-control.admission-controller.name" $ }}-{{ $name }}
  namespace: {{ template "cloud-control.namespace" $ }}
  labels:
    control-plane: controller-manager
  {{- include "cloud-control.admission-controller.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "cloud-control.admission-controller.config.imagePullSecret" $secret }}
{{ end }}
{{- end }}
