{{- if .Values.admissionController.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "cloud-control.admission-controller.name" . }}-leader-election-role
  namespace: {{ template "cloud-control.namespace" . }}
  labels:
  {{- include "cloud-control.admission-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "cloud-control.admission-controller.name" . }}-leader-election-rolebinding
  namespace: {{ template "cloud-control.namespace" . }}
  labels:
  {{- include "cloud-control.admission-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "cloud-control.admission-controller.name" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ template "cloud-control.admission-controller.serviceAccountName" . }}
  namespace: {{ template "cloud-control.namespace" . }}
{{- end }}