{{- if .Values.admissionController.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "cloud-control.admission-controller.name" . }}-manager-role
  labels:
  {{- include "cloud-control.admission-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ''
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nirmata.io
  resources:
  - imageverificationpolicies
  - validatingpolicies
  - awsaccountconfigs
  - awsorgconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nirmata.io
  resources:
  - proxies
  - preprocessors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nirmata.io
  resources:
  - proxies/finalizers
  verbs:
  - update
- apiGroups:
  - nirmata.io
  resources:
  - proxies/status
  - preprocessors/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "cloud-control.admission-controller.name" . }}-manager-rolebinding
  labels:
  {{- include "cloud-control.admission-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "cloud-control.admission-controller.name" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ template "cloud-control.admission-controller.serviceAccountName" . }}
  namespace: {{ template "cloud-control.namespace" . }}
{{- end }}