apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "cloud-control.admission-controller.name" . }}-proxy-viewer-role
  labels:
  {{- include "cloud-control.admission-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - nirmata.io
  resources:
  - proxies
  - preprocessors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nirmata.io
  resources:
  - proxies/status
  - preprocessors/status
  verbs:
  - get