name: Lint and Test Charts

permissions:
  contents: read

on:
  push:
    branches-ignore:
      - main
      - 'release-*'
    tags:
      - 'v*'

jobs:
  lint:
    uses: ./.github/workflows/chart-lint.yml