name: Lint and Test Charts

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - 'release-*'
  push:
    branches-ignore:
      - main
      - 'release-*'
    tags:
      - 'v*'

jobs:
  lint:
    uses: ./.github/workflows/chart-lint.yml
