name: Lint and Test Charts

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - 'release-*'
  push:
    branches-ignore:
      - main
      - 'release-*'
    tags:
      - 'v*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Charts
        uses: ./.github/actions/chart-lint
        with:
          target-branch: main