name: Lint and Test Charts

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - 'release-*'
  push:
    branches-ignore:
      - main
      - 'release-*'
    tags:
      - 'v*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine target branch for comparison
        id: target-branch
        run: |
          if [[ "${{ github.ref }}" == refs/heads/release-* ]]; then
            echo "target-branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "target-branch=main" >> $GITHUB_OUTPUT
          fi

      - name: Show target branch
        run: |
          echo "Using target-branch: ${{ steps.target-branch.outputs.target-branch }}"

      - name: Lint Charts
        uses: ./.github/actions/chart-lint
        with:
          target-branch: ${{ steps.target-branch.outputs.target-branch }}