name: Lint and Test Charts

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - 'release-*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine target branch for comparison
        id: target-branch
        run: |
          echo "target-branch=${{ github.base_ref }}" >> $GITHUB_OUTPUT

      - name: Lint Charts
        uses: ./.github/actions/chart-lint
        with:
          target-branch: ${{ steps.target-branch.outputs.target-branch }}