name: Lint and Test Charts

on:
  pull_request:
    branches:
      - main
      - 'release-*'
  push:
    branches-ignore:
      - main
      - 'release-*'
    tags:
      - 'v*'

jobs:
  lint:
    uses: ./.github/workflows/chart-lint.yml
