name: Lint and Test Charts

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - 'release-*'
  push:
    branches-ignore:
      - main
      - 'release-*'
    tags:
      - 'v*'

jobs:
  lint:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/chart-lint.yml